### ISSUE TITLE
Get bookmarks tool working

### ISSUE THREAD

**Issue by destinationtoast** [esgibter/fandomstats#44]
I just tried to add a new HTML page to the site (bookmarks.html) and I have no idea if I did it right.  (In part because the Hover but popped up again.)  My goal is that fandomstats.com/bookmarks.html should show my AO3 bookmarks tool.  I'll track this issue until I have it working right.

**Comment by destinationtoast** [comment]
Hover is back, so I tested the URL: http://fandomstats.com/bookmarks.html
It gives me an error message.  I need to figure out how to actually serve this page.

**Comment by esgibter** [comment]
It sounds like you didn't push to prod, yup. Bookmarks showed up for you locally?

**Comment by esgibter** [comment]
(deploying the app should happen with the command `appcfg.py update src/` )

**Comment by annathecrow** [comment]
Bookmark tool works now, so I'm gonna close this. :)

Because this isn't immediately obvious: I folded up the bookmark tool into the main (`home`) site templates. The code of @destinationtoast original bookmarks.html is now in `src/application/home/templates/bookmark-viewer.html`([here](https://github.com/esgibter/fandomstats/blob/4b170817b3ce44b017c50f84c353bdf6633e2e15/src/application/home/templates/bookmark-viewer.html)) - it uses some jinja2 (Flask's templating language of choice) but the important parts are still vanilla HTML and JavaScript.

(I kept the original file and folder for reference, but we can delete it if you don't need it.)
